# fly.toml app configuration file generated for truegain-api on 2023-10-15T18:04:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "truegain-api"
primary_region = "arn"

[build]
  image = "qualle34/truegain-api:v0.1.4"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
