version: '3.1'

services:

  truegain-api:
    image: "qualle34/truegain-api:v0.1.6"
    environment:
      TRUEGAIN_DB_URL: "jdbc:postgresql://172.20.0.3:5432/truegain"
      TRUEGAIN_DB_USERNAME: "qualle"
      TRUEGAIN_DB_PASSWORD: "43q21"
    networks:
      - truegain-net
    ports:
      - "8080:8080"

  truegain-db:
    image: postgres
    networks:
      - truegain-net
    environment:
      POSTGRES_DB: "truegain"
      POSTGRES_USER: "qualle"
      POSTGRES_PASSWORD: "43q21"
    ports:
      - "5432:5432"

networks:
  truegain-net: