server:
  port: 8080
spring:
  application:
    name: truegain-api
  datasource:
    password:  ${TRUEGAIN_DB_PASSWORD:43q21}
    username:  ${TRUEGAIN_DB_USERNAME:qualle}
    url:  ${TRUEGAIN_DB_URL:jdbc:postgresql://localhost:5432/truegain}
    hikari:
      connection-timeout: 10000
      validation-timeout: 2000
      maximum-pool-size: 20
  flyway:
    baseline-on-migrate: true
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  rabbitmq:
    password: password
    username: user

authentication:
  token:
    issued-by: ${TRUEGAIN_AUTH_TOKEN_ISSUED:truegain-api}
    lifetime: ${TRUEGAIN_AUTH_TOKEN_LIFETIME:30m}
    secret: ${TRUEGAIN_AUTH_TOKEN_SECRET:QFQ1HVPw53Xjlv2Is4oO9mIrG7LYq4WOKZBW820t1b0=}
  session:
    lifetime: ${TRUEGAIN_AUTH_SESSION_LIFETIME:30d}
  temporary:
    lifetime: ${confirmation.lifetime}

confirmation:
  email:
    enable: ${TRUEGAIN_EMAIL_ENABLE:false}
    login: ${TRUEGAIN_EMAIL_LOGIN:qualle.inc@gmail.com}
    password: ${TRUEGAIN_EMAIL_PASSWORD:aaa}
  lifetime: ${TRUEGAIN_CONFIRM_LIFETIME:1d}

management:
  endpoints:
    web:
      exposure:
        include: httptrace,health,info,prometheus
