server:
  port: 8080
spring:
  application:
    name: truegain-api
  datasource:
    password:  ${TRUEGAIN_DB_PASSWORD:43q21}
    username:  ${TRUEGAIN_DB_USERNAME:qualle}
    url:  ${TRUEGAIN_DB_URL:jdbc:postgresql://localhost:5432/truegain}
    hikari:
      connection-timeout: 10000
      validation-timeout: 2000
      maximum-pool-size: 20
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

authentication:
  token:
    issued-by: ${TRUEGAIN_AUTH_TOKEN_ISSUED:truegain-api}
    lifetime: ${TRUEGAIN_AUTH_TOKEN_LIFETIME:30m}
    secret: ${TRUEGAIN_AUTH_TOKEN_SECRET:QFQ1HVPw53Xjlv2Is4oO9mIrG7LYq4WOKZBW820t1b0=}
  session:
    lifetime: ${TRUEGAIN_AUTH_SESSION_LIFETIME:30d}
  temporary:
    lifetime: ${TRUEGAIN_AUTH_TEMP_LIFETIME:1d}

email:
  enable: ${TRUEGAIN_EMAIL_ENABLE:true}
  login: ${TRUEGAIN_EMAIL_LOGIN:qualle.inc@gmail.com}
  password: ${TRUEGAIN_EMAIL_PASSWORD:aaa}

management:
  endpoints:
    web:
      exposure:
        include: httptrace,health,info,beans
