server:
  port: 8080
spring:
  application:
    name: truegain-api
  datasource:
    password:  ${TRUEGAIN_DB_PASSWORD:43q21}
    username:  ${TRUEGAIN_DB_USERNAME:qualle}
    url:  ${TRUEGAIN_DB_URL:jdbc:postgresql://localhost:5432/truegain}
    hikari:
      max-lifetime: 1000
      connection-timeout: 5000
      validation-timeout: 1000
      idle-timeout: 30000
      maximum-pool-size: 20
  sql:
    init:
      mode: always
  jpa:
    show-sql: true


