server:
  port: 8080
spring:
  application:
    name: truegain-api
  datasource:
    password:  ${TRUEGAIN_DB_PASSWORD:43q21}
    username:  ${TRUEGAIN_DB_USERNAME:qualle}
    url:  ${TRUEGAIN_DB_URL:jdbc:postgresql://localhost:5432/truegain}
    hikari:
      connection-timeout: 10000
      validation-timeout: 2000
      maximum-pool-size: 20
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

authentication:
  token:
    issued-by: truegain-api
    lifetime: 30m
    secret: QFQ1HVPw53Xjlv2Is4oO9mIrG7LYq4WOKZBW820t1b0=
  session:
    lifetime: 30d

management:
  endpoints:
    web:
      exposure:
        include: httptrace,health,info,beans
