name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Maven deploy phase
        run: mvn --batch-mode --update-snapshots install
      - name: Build Docker image
        run: docker build -t qualle34/truegain-api:latest -f backend/Dockerfile backend
      - name: Log in to Docker Hub
        run: echo "${DOCKER_TOKEN}" | docker login --username qualle34 --password-stdin
      - name: Push Docker image to Docker Hub
        run: docker push qualle34/truegain-api:latest
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
