name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Pull image
        run: mvn --batch-mode deploy
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}